[[blockchain]]
blockchain = "stellar"
network = "testnet"
endpoint = "https://horizon-testnet.stellar.org"
asset_list = "assets/stellar/testnet.toml"

[[blockchain]]
blockchain = "bitcoin"
network = "test"
endpoint = "https://test.xlm.fish"
asset_list = "assets/bitcoin/test.toml"

[[blockchain]]
blockchain = "litecoin"
network = "test"
endpoint = "https://litecoin.xlm.fish"
asset_list = "assets/litecoin/test.toml"
