# Config.toml
# Minimal configuration per chain

[chains.stellar]
chain_name = "Stellar"
api_endpoint = "https://horizon.stellar.org"
asset_list = "assets/stellar/testnet.toml"

# [chains.xrp]
# chain_name = "XRP Ledger"
# api_endpoint = "https://s1.ripple.com:51234/"
# asset_list = "assets/xrp/testnet.toml"

