[[asset]]
label = "XLM Fish Token"
code = "XLMFISH"
issuer = "GAX3YQC26LTS6NLW2QGRQC4MK24XKL5JLZ7KFHNERWPC3HKYYYABTEMT"

[[asset]]
label = "USD Coin"
code = "USDC"
issuer = "GA5ZSEJYB37JFN3PL2M5WTZ5YJY4OOGUO5ON5C6H7Q5HL5EY7AXXXXXX"

[[asset]]
label = "Testnet Token"
code = "ATKN"
issuer = "GXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

